# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from randomizer import randomizer_pb2 as randomizer__pb2

GRPC_GENERATED_VERSION = "1.66.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in randomizer_pb2_grpc.py depends on"  # noqa: F541
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class RandomizerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RandomNumber = channel.unary_unary(
            "/randomizer.Randomizer/RandomNumber",
            request_serializer=randomizer__pb2.AddRequest.SerializeToString,
            response_deserializer=randomizer__pb2.AddResponse.FromString,
            _registered_method=True,
        )


class RandomizerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RandomNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RandomizerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "RandomNumber": grpc.unary_unary_rpc_method_handler(
            servicer.RandomNumber,
            request_deserializer=randomizer__pb2.AddRequest.FromString,
            response_serializer=randomizer__pb2.AddResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "randomizer.Randomizer", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("randomizer.Randomizer", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Randomizer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RandomNumber(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/randomizer.Randomizer/RandomNumber",
            randomizer__pb2.AddRequest.SerializeToString,
            randomizer__pb2.AddResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
