# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: randomizer.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 27, 2, "", "randomizer.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10randomizer.proto\x12\nrandomizer"\x0c\n\nAddRequest"\x1d\n\x0b\x41\x64\x64Response\x12\x0e\n\x06result\x18\x01 \x01(\x02\x32M\n\nRandomizer\x12?\n\x0cRandomNumber\x12\x16.randomizer.AddRequest\x1a\x17.randomizer.AddResponseb\x06proto3'  # noqa: E501
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "randomizer_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_ADDREQUEST"]._serialized_start = 32
    _globals["_ADDREQUEST"]._serialized_end = 44
    _globals["_ADDRESPONSE"]._serialized_start = 46
    _globals["_ADDRESPONSE"]._serialized_end = 75
    _globals["_RANDOMIZER"]._serialized_start = 77
    _globals["_RANDOMIZER"]._serialized_end = 154
# @@protoc_insertion_point(module_scope)
