# Our main server code uses autogenerated scripts
import random
from concurrent import futures

import grpc

from db import session
from db.models import GeneratedNumbers
from randomizer import randomizer_pb2, randomizer_pb2_grpc


class RandomizerServicer(randomizer_pb2_grpc.RandomizerServicer):
    def RandomNumber(self, request, context):
        result = random.random()
        db_entry = GeneratedNumbers(number=result)
        session.add(db_entry)
        session.commit()
        return randomizer_pb2.AddResponse(result=result)


def serve():
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    randomizer_pb2_grpc.add_RandomizerServicer_to_server(RandomizerServicer(), server)
    server.add_insecure_port("[::]:50051")
    server.start()
    server.wait_for_termination()


if __name__ == "__main__":
    serve()
